import { Card, CardSet } from './types'

// ---------------------------------------------------------------------------
// Real card data (generated by scripts/fetch-card-data.mjs +
// scripts/generate-card-data.mjs).  When present, this replaces mock data.
// ---------------------------------------------------------------------------
let _realCards: Card[] | null = null
let _realSets: CardSet[] | null = null
try {
  // Dynamic require so the build doesn't error when the file doesn't exist yet
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const cardsJson = require('./cards-generated.json') as Card[]
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const setsJson = require('./sets-generated.json') as CardSet[]
  _realCards = cardsJson
  _realSets = setsJson
} catch {
  // File not generated yet — fall through to mock data below
}

// ---------------------------------------------------------------------------
// Mock data (used until real data is generated)
// ---------------------------------------------------------------------------
const SETS: CardSet[] = [
  { setCode: 'OP01', setName: 'Romance Dawn', releaseDate: '2022-07-22', releaseOrder: 1 },
  { setCode: 'OP02', setName: 'Paramount War', releaseDate: '2022-11-04', releaseOrder: 2 },
  { setCode: 'OP03', setName: 'Pillars of Strength', releaseDate: '2023-03-10', releaseOrder: 3 },
  { setCode: 'OP04', setName: 'Kingdoms of Intrigue', releaseDate: '2023-06-30', releaseOrder: 4 },
  { setCode: 'OP05', setName: 'Awakening of the New Era', releaseDate: '2023-08-25', releaseOrder: 5 },
  { setCode: 'OP06', setName: 'Wings of the Captain', releaseDate: '2023-11-10', releaseOrder: 6 },
  { setCode: 'OP07', setName: '500 Years in the Future', releaseDate: '2024-02-09', releaseOrder: 7 },
  { setCode: 'OP08', setName: 'Two Legends', releaseDate: '2024-05-24', releaseOrder: 8 },
  { setCode: 'OP09', setName: 'The Four Emperors', releaseDate: '2024-08-30', releaseOrder: 9 },
]

const CARD_TYPES = ['Leader', 'Character', 'Event', 'Stage']
const RARITIES = ['C', 'UC', 'R', 'SR', 'SEC', 'L']
const COLORS = ['Red', 'Blue', 'Green', 'Purple', 'Black', 'Yellow']
const NAMES = [
  'Monkey D. Luffy', 'Roronoa Zoro', 'Nami', 'Usopp', 'Sanji',
  'Tony Tony Chopper', 'Nico Robin', 'Franky', 'Brook', 'Jinbe',
  'Shanks', 'Trafalgar Law', 'Portgas D. Ace', 'Kaido', 'Big Mom',
  'Boa Hancock', 'Doflamingo', 'Crocodile', 'Katakuri', 'Marco',
  'Sabo', 'Yamato', 'Whitebeard', 'Blackbeard', 'Aokiji',
  'Kizaru', 'Akainu', 'Garp', 'Rayleigh', 'Roger',
  'Buggy', 'Mihawk', 'Kid', 'Killer', 'Bonney',
  'Bartolomeo', 'Cavendish', 'Koby', 'Smoker', 'Tashigi',
]

function seededRandom(seed: number) {
  const x = Math.sin(seed) * 10000
  return x - Math.floor(x)
}

function generateCards(): Card[] {
  const cards: Card[] = []
  let globalIndex = 0

  for (const set of SETS) {
    const cardsInSet = 40 + Math.floor(seededRandom(set.releaseOrder * 7) * 30)

    for (let i = 0; i < cardsInSet; i++) {
      const seed = globalIndex + 1
      const nameIndex = Math.floor(seededRandom(seed * 3) * NAMES.length)
      const typeIndex = Math.floor(seededRandom(seed * 5) * CARD_TYPES.length)
      const rarityIndex = Math.floor(seededRandom(seed * 7) * RARITIES.length)
      const colorIndex = Math.floor(seededRandom(seed * 11) * COLORS.length)
      const cardNum = String(i + 1).padStart(3, '0')

      cards.push({
        id: `${set.setCode}-${cardNum}`,
        code: `${set.setCode}-${cardNum}`,
        name: NAMES[nameIndex],
        setCode: set.setCode,
        setName: set.setName,
        releaseDate: set.releaseDate,
        releaseOrder: set.releaseOrder,
        cardType: CARD_TYPES[typeIndex],
        rarity: RARITIES[rarityIndex],
        colors: [COLORS[colorIndex]],
        imageSmall: `https://picsum.photos/seed/${set.setCode}${cardNum}/400/560`,
        imageLarge: `https://picsum.photos/seed/${set.setCode}${cardNum}/800/1120`,
      })
      globalIndex++
    }
  }

  return cards
}

let _cards: Card[] | null = null
let _sets: CardSet[] | null = null

export function getCards(): Card[] {
  if (_realCards) return _realCards
  if (!_cards) _cards = generateCards()
  return _cards
}

export function getSets(): CardSet[] {
  if (_realSets) return _realSets
  if (!_sets) _sets = [...SETS]
  return _sets
}

export function getCardsBySet(setCode: string): Card[] {
  return getCards().filter(c => c.setCode === setCode)
}
