// Card-wall pricing helpers. Reads the JSON files emitted by the
// op_hub pricing pipeline (sibling Python project) and exposes a
// typed, lookup-friendly surface for the tile, lightbox, and sealed-
// box dashboard.
//
// All four JSON files live next to the cards/sets bundles under
// src/lib/. They are gitignored and regenerated by `op-hub pricing
// export-card-wall`, which runs after each daily sync on the VPS.

import { useEffect, useState } from 'react'

export type GradedRow = {
  grader: string          // psa | bgs | cgc | tag | sgc | ace
  grade: string           // "10" / "9" / "9.5"
  avg1d: number | null
  avg7d: number | null
  avg30d: number | null
  // ``display`` is what the UI renders.
  //   number      → use this value (already drift-corrected if needed)
  //   null        → cell was HARD-suppressed by the export-time sanity
  //                 layer (monotonicity / cross-grader / raw-vs-graded
  //                 violation). UI renders "-" with a tooltip explaining
  //                 the failed check.
  //   undefined   → no display layer ran (old bundle); UI falls back
  //                 through avg30d → avg7d → avg1d.
  display?: number | null
  // True iff ``display`` came from avg7d/1d instead of avg30d.
  // UI dims drifted cells and shows a "limited recent data" tooltip.
  drifted?: boolean
  // True iff the export's sanity layer hid this cell. Distinguishes
  // "no data" (cell missing entirely) from "data is wrong, hidden".
  suppressed?: boolean
  // Human-readable tooltip text explaining why the cell was hidden.
  // E.g. "BGS 10 ($210) below BGS 9.5 ($440) - impossible ladder".
  suppressReason?: string
  // Machine-readable list of rule codes that fired
  // (monotonicity, raw_above_graded, cross_grader_outlier).
  suppressedBy?: string[]
}

export type EbayRawRow = {
  avg1d: number | null
  avg7d: number | null
  avg30d: number | null
}

/** One side of an errata card's split pricing (pre- or post-print). */
export type ErrataPrinting = {
  kind: 'pre' | 'post'
  title: string
  subtitle: string
  primaryMarket: number | null
  primarySubtype?: string | null
  listings?: number | null
  syncedAt: string
  history: [number, number][]
  graded: GradedRow[]
  flags?: string[]
}

export type CardPricing = {
  tcgplayerId: number
  cardCode: string | null
  name: string
  rarity: string | null
  setAbbr: string | null
  syncedAt: string
  // Primary price source. 'tcgplayer' = op_hub pipeline; 'ebay' = eBay
  // Browse active listings (used for Gundam and other non-OP collections
  // that don't yet have a TCGPlayer integration).
  source?: 'tcgplayer' | 'ebay'
  // TCGPlayer subtype -> price block. Subtype keys include "Normal",
  // "Foil", "Holofoil", "Unopened", etc. We render whichever exists.
  raw: Record<string, { market: number | null; low: number | null; high: number | null }>
  graded: GradedRow[]
  ebayRaw: Record<string, EbayRawRow>
  // Pre-resolved best market (Foil > Holo > Normal precedence). Used by
  // the tile badge so it doesn't have to know subtype priority.
  primaryMarket: number | null
  // Which raw subtype (Foil / Normal / Holofoil ...) primaryMarket
  // came from. Used to label the hero price as "Foil market" etc.
  primarySubtype?: string | null
  // Total NM English listing count across SKUs - used as the "real
  // data" gate (we hide prices when listings are too thin).
  listings?: number
  // Quality flags raised by the export-time sanity layer. Possible
  // values:
  //   - "phantom_market"     : raw TCGPlayer market is > 3x the highest
  //                            graded eBay average, implying the raw
  //                            listing has no real sales backing it
  //                            (common for Treasure Cup promo prints).
  //   - "graded_inconsistent": at least one grader's ladder violates
  //                            monotonicity (e.g. PSA 10 < PSA 9), so
  //                            we don't fully trust those graded cells.
  // The UI down-weights or annotates affected sections accordingly.
  flags?: string[]
  // Matcher metadata. The catalog matcher pairs each wall_card_id to a
  // TCGPlayer product using set hints + tag priority. When the bundle's
  // distribution declares a Bandai set in [SETCODE] form we honor that
  // as a hard constraint; otherwise we fall back to positional pairing
  // which is more likely to mis-attribute (e.g. assign an OP01 original
  // print to a wall slot whose bundle says PRB-01 reprint). `matchMethod`
  // and `matchConfidence` surface the result so the UI can warn / hide.
  //
  //  - "exact_base"           : base prints, conf 1.0
  //  - "exact_variant"        : sole variant pair, conf 1.0
  //  - "set_hint_match"       : set-constrained variant pair, conf 0.95
  //  - "heuristic_p1"         : positional fallback, conf 0.6
  //  - "cross_set_fallback"   : hint declared but no in-set candidate;
  //                             paired across sets, conf 0.4 (likely
  //                             wrong; UI should label as "Verify")
  matchMethod?: string | null
  matchConfidence?: number | null
  // When the card is on Bandai's errata list, export attaches a split
  // view: post-errata raw TCGPlayer market + pre-errata graded slab
  // comps, each with its own sparkline.
  errataPrintings?: {
    pre: ErrataPrinting
    post: ErrataPrinting
  }
}

export type PricingBundle = {
  syncedAt: string
  cards: Record<string, CardPricing>   // keyed by wall card id (e.g. OP01-001 or OP01-001_p1)
}

export type PricingHistoryBundle = {
  syncedAt: string
  series: Record<string, [number, number][]>   // wallCardId -> [unix_ms, market]
}

export type BoxPricing = {
  tcgplayerId: number
  setAbbr: string
  name: string
  imageUrl: string | null
  market: number | null
  low: number | null
  high: number | null
  listings: number | null
  syncedAt: string
  history: [number, number][]
}

export type BoxesBundle = {
  syncedAt: string
  boxes: Record<string, BoxPricing>
}

export type PricingMeta = {
  writtenAt: string
  lastSuccessful: Record<string, string>
  counts: {
    cards: number
    matchedToWall: number
    withGraded: number
    boxes: number
  }
}

// ---------------------------------------------------------------------------
// Loader strategy
// ---------------------------------------------------------------------------
//
// pricing-meta.json stays bundled synchronously via require(): it's ~250B
// and the Header reads it on every page so paying a tiny static cost is
// preferable to a fetch round-trip on initial paint.
//
// The three heavy bundles (pricing, history, boxes) are loaded lazily via
// dynamic import(), which webpack/Turbopack splits into separate async
// chunks. None of them ship with the home-route bundle; they only land
// when a UI surface actually needs them:
//   - pricing-one-piece.json : when the prices toggle is on OR the
//                              lightbox opens (PricePanel triggers load)
//   - price-history-...json  : when the lightbox opens
//   - pricing-boxes-...json  : when /sealed mounts
//
// Each loader memoises its in-flight promise + the resolved bundle, so
// repeat calls are free. Sync getters return the cached data once loaded,
// `null` / `[]` before. Components use the `useEnsure*Loaded` hooks to
// trigger the load + re-render when ready.
//
// require() inside try/catch keeps prod builds working before the first
// cron run has emitted the JSON files (matches the old data.ts pattern).

let _meta: PricingMeta | null = null
try {
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  _meta = require('./pricing-meta.json') as PricingMeta
} catch {
  _meta = null
}

// Cached, resolved bundles. null = not yet loaded (or load failed).
let _pricingCache: PricingBundle | null = null
let _historyCache: PricingHistoryBundle | null = null
let _boxesCache: BoxesBundle | null = null
let _boxesSorted: BoxPricing[] | null = null

// In-flight load promises (one-shot - memoised after first call).
let _pricingPromise: Promise<PricingBundle> | null = null
let _historyPromise: Promise<PricingHistoryBundle> | null = null
let _boxesPromise: Promise<BoxesBundle> | null = null

const EMPTY_PRICING: PricingBundle = { syncedAt: '', cards: {} }
const EMPTY_HISTORY: PricingHistoryBundle = { syncedAt: '', series: {} }
const EMPTY_BOXES: BoxesBundle = { syncedAt: '', boxes: {} }

export function loadPricing(): Promise<PricingBundle> {
  if (_pricingCache) return Promise.resolve(_pricingCache)
  if (!_pricingPromise) {
    _pricingPromise = import('./pricing-one-piece.json')
      .then((m) => {
        _pricingCache = (m.default ?? m) as unknown as PricingBundle
        return _pricingCache
      })
      .catch(() => {
        _pricingCache = EMPTY_PRICING
        return EMPTY_PRICING
      })
  }
  return _pricingPromise
}

export function loadHistory(): Promise<PricingHistoryBundle> {
  if (_historyCache) return Promise.resolve(_historyCache)
  if (!_historyPromise) {
    _historyPromise = import('./price-history-one-piece.json')
      .then((m) => {
        _historyCache = (m.default ?? m) as unknown as PricingHistoryBundle
        return _historyCache
      })
      .catch(() => {
        _historyCache = EMPTY_HISTORY
        return EMPTY_HISTORY
      })
  }
  return _historyPromise
}

export function loadBoxes(): Promise<BoxesBundle> {
  if (_boxesCache) return Promise.resolve(_boxesCache)
  if (!_boxesPromise) {
    _boxesPromise = import('./pricing-boxes-one-piece.json')
      .then((m) => {
        _boxesCache = (m.default ?? m) as unknown as BoxesBundle
        return _boxesCache
      })
      .catch(() => {
        _boxesCache = EMPTY_BOXES
        return EMPTY_BOXES
      })
  }
  return _boxesPromise
}

// ---------------------------------------------------------------------------
// Gundam pricing bundle (eBay-sourced, generated by fetch-gundam-pricing.mjs)
// ---------------------------------------------------------------------------

let _gundamPricingCache: PricingBundle | null = null
let _gundamPricingPromise: Promise<PricingBundle> | null = null

export function loadGundamPricing(): Promise<PricingBundle> {
  if (_gundamPricingCache) return Promise.resolve(_gundamPricingCache)
  if (!_gundamPricingPromise) {
    _gundamPricingPromise = import('./pricing-gundam.json')
      .then((m) => {
        _gundamPricingCache = (m.default ?? m) as unknown as PricingBundle
        return _gundamPricingCache
      })
      .catch(() => {
        _gundamPricingCache = EMPTY_PRICING
        return EMPTY_PRICING
      })
  }
  return _gundamPricingPromise
}

export function getGundamCardPricing(wallCardId: string): CardPricing | null {
  return _gundamPricingCache?.cards[wallCardId] ?? null
}

export function useEnsureGundamPricingLoaded(): boolean {
  return useReady(() => _gundamPricingCache !== null, loadGundamPricing)
}

// ---------------------------------------------------------------------------
// Collection-aware helpers — so callers don't branch on collection themselves
// ---------------------------------------------------------------------------

export function loadPricingForCollection(collection: string): Promise<PricingBundle> {
  if (collection === 'one-piece') return loadPricing()
  if (collection === 'gundam') return loadGundamPricing()
  return Promise.resolve(EMPTY_PRICING)
}

export function getCardPricingForCollection(
  collection: string,
  wallCardId: string,
): CardPricing | null {
  if (collection === 'one-piece') return getCardPricing(wallCardId)
  if (collection === 'gundam') return getGundamCardPricing(wallCardId)
  return null
}

export function useEnsurePricingLoadedForCollection(collection: string): boolean {
  const opReady = useEnsurePricingLoaded()
  const gundamReady = useEnsureGundamPricingLoaded()
  if (collection === 'one-piece') return opReady
  if (collection === 'gundam') return gundamReady
  return true
}

// Public sync lookups --------------------------------------------------------
//
// Return cached data when present, otherwise the "empty" fallback. Callers
// that care about reactive readiness should pair these with the
// `useEnsure*Loaded` hooks below - the hook triggers the load and forces a
// re-render once the cache is populated.

export function getCardPricing(wallCardId: string): CardPricing | null {
  return _pricingCache?.cards[wallCardId] ?? null
}

export function getCardHistory(wallCardId: string): [number, number][] {
  return _historyCache?.series[wallCardId] ?? []
}

export function getBoxes(): BoxPricing[] {
  if (!_boxesCache) return []
  // Memoise the sorted list - BoxDetail re-queries on every render and the
  // unsorted bag is rebuilt + sorted on each call otherwise.
  if (_boxesSorted) return _boxesSorted
  _boxesSorted = Object.values(_boxesCache.boxes).sort((a, b) => {
    const sa = a.setAbbr || ''
    const sb = b.setAbbr || ''
    if (sa !== sb) return sa.localeCompare(sb)
    return (a.name || '').localeCompare(b.name || '')
  })
  return _boxesSorted
}

export function getBox(tcgplayerId: number | string): BoxPricing | null {
  return _boxesCache?.boxes[String(tcgplayerId)] ?? null
}

export function getPricingMeta(): PricingMeta | null {
  return _meta
}

export function getPricingSyncedAt(): string | null {
  return _pricingCache?.syncedAt || null
}

// React readiness hooks ------------------------------------------------------
//
// Each hook triggers its bundle load on first mount and returns a boolean
// that flips true once the cache is populated. We deliberately keep these
// in pricing.ts so consumers only import one module (and the load
// memoisation lives next to its cache).

function useReady(
  isCached: () => boolean,
  load: () => Promise<unknown>,
): boolean {
  const [ready, setReady] = useState<boolean>(() => isCached())
  useEffect(() => {
    if (isCached()) {
      if (!ready) setReady(true)
      return
    }
    let mounted = true
    load().then(() => {
      if (mounted) setReady(true)
    })
    return () => {
      mounted = false
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])
  return ready
}

export function useEnsurePricingLoaded(): boolean {
  return useReady(() => _pricingCache !== null, loadPricing)
}

export function useEnsureHistoryLoaded(): boolean {
  return useReady(() => _historyCache !== null, loadHistory)
}

export function useEnsureBoxesLoaded(): boolean {
  return useReady(() => _boxesCache !== null, loadBoxes)
}

// Display helpers ------------------------------------------------------------

const NF_USD = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD',
  maximumFractionDigits: 2,
})
const NF_USD_K = new Intl.NumberFormat('en-US', {
  style: 'currency',
  currency: 'USD',
  maximumFractionDigits: 0,
})

export function formatUsd(n: number | null | undefined): string {
  if (n === null || n === undefined || Number.isNaN(n)) return '-'
  return n >= 1000 ? NF_USD_K.format(n) : NF_USD.format(n)
}

export function formatUsdCompact(n: number | null | undefined): string {
  if (n === null || n === undefined || Number.isNaN(n)) return '-'
  if (n >= 1000) return `$${(n / 1000).toFixed(1)}k`
  if (n >= 100) return `$${n.toFixed(0)}`
  return `$${n.toFixed(2)}`
}

// Format an ISO timestamp as a relative "2h ago" or "yesterday" string.
export function formatRelative(iso: string | null | undefined): string {
  if (!iso) return ''
  const then = Date.parse(iso)
  if (Number.isNaN(then)) return ''
  const deltaS = Math.max(0, (Date.now() - then) / 1000)
  if (deltaS < 60) return 'just now'
  if (deltaS < 3600) return `${Math.floor(deltaS / 60)}m ago`
  if (deltaS < 86400) return `${Math.floor(deltaS / 3600)}h ago`
  if (deltaS < 86400 * 2) return 'yesterday'
  return `${Math.floor(deltaS / 86400)}d ago`
}

// Stable grader display order used by the lightbox table.
export const GRADER_ORDER: string[] = ['psa', 'bgs', 'cgc', 'sgc', 'tag', 'ace']

// Group graded rows by grader so the lightbox can render one row per
// grader with grade columns. We collapse to a small set of "interesting"
// grades (10, 9.5, 9) so the table stays compact.
export const DISPLAY_GRADES: string[] = ['10', '9.5', '9']

export function groupGradedByGrader(
  rows: GradedRow[],
): Map<string, Map<string, GradedRow>> {
  const out = new Map<string, Map<string, GradedRow>>()
  for (const r of rows) {
    if (!out.has(r.grader)) out.set(r.grader, new Map())
    const sub = out.get(r.grader)!
    if (!sub.has(r.grade)) sub.set(r.grade, r)
  }
  return out
}
